### ISSUE TITLE
error due to the number of elements in the data structure defined

### ISSUE THREAD

**Issue by relhamoud** [Saptarshi-Sarkar/OC3-Hywind-Spar#2]
Hello @Saptarshi-Sarkar,

I was running the code of OC3 Hywind from your repository.
However, i am getting an error stating that the right side and the left side of an equation have not the same number of elements. The right side is a 3D array and the left one is a struct containing 4 fields. 

The following figure shows the error i obtain:

![Capture](https://github.com/Saptarshi-Sarkar/OC3-Hywind-Spar/assets/106849956/76738cac-f993-4496-89fe-1ebea21eb05d)

Could you please help me ?

Best Regards,

**Comment by Saptarshi-Sarkar** [comment]
Hi @relhamoud 
Apologies for the delay in response. 
The code seems to work if you have the correct TurbSim wind files. 
From the error above it seems that something went wrong in getting the correct wind speeds. 

I have uploaded example TurbSim .wnd and .sum files in the "Wind_Dataset" folder. Please enter the name of this file "NTM_A" in the main MATLAB script in the line shown below:

`% Get the TurbSim-generated wind field and grid
[velocity, Wind.y, Wind.z, Wind.nz, Wind.ny, Wind.dz,...
          Wind.dy, Wind.dt, Wind.zHub, Wind.z1, Wind.SummVars] = readBLgrid('1ETMC');`

Your code should run. If it doesn't, using these wind files, please reach out with more detail and I will help you.

**Comment by relhamoud** [comment]
Thank you so much. It works now. 👌👌👌👌
